### ISSUE TITLE
Include the title crawl embedded HTML

### ISSUE THREAD

**Issue by bheiskell** [wrycu/StarWarsFFG-Enhancements#3]
https://github.com/bheiskell/star-wars-crawl

- [x] Include configuration to upload/select potentially copy written assets. Do not include copy written assets in this repo.
- [x] Use activeListeners to mutate the HTML content, updating: text, audio, and images
- [x] Add support for localization
- [x] Create a function to parse a Journal into the format the socket is expecting to be emitted
- [x] Create a form that prompts the user to select a Journal from a set of Journals in a provided folder
- [x] Add a configuration option to select a Journal folder to use as the source for the opening-crawl
- [x] Add a button somewhere to launch the opening-crawl (currently thinking scene-control tool bar, but that feels a little wrong)
- [x] Include a way to create a templated Journal to minimize documentation needed to configure the opening crawl.
- [x] Integrate with Foundry's AudioHelper to preload the audio file rather than using an embedded audio tag.
- [x] Use [file picker](https://gitlab.com/foundry-azzurite/settings-extender) to select the music and logo
- [x] Default the Opening Crawls folder and prompt if it doesn't exist
- [x] Combine the create Opening Crawl button with the Launch to just have an Opening Crawl form

**Comment by bheiskell** [comment]
Dealing with the copyrighted assets took a lot longer than I thought, but I have reasonably high confidence that there isn't anything suspect checked into the repository. I went ahead and included some fonts not used by the opening crawl, but will support me in later issues related to the datapads.

Modifying the CSS/HTML to use safer resources took longer than I thought, and mostly ended up resulting in me using the original Kassel Labs assets. Converting the iframe solution to embedding the HTML in a `Application` took a while, as many of the CSS rules were sized off the total view port and position absolutes and clipping were behaving erratically. I've sorted that out.

Additionally, I've wired up the basics of using a socket to launch an Application with HTML/CSS contents. I've pushed my current work in progress. Here's my current TODO:

- [ ] Use activeListeners to mutate the HTML content, updating: text, audio, and images
- [ ] Create a function to parse a Journal into the format the socket is expecting to be emitted
- [ ] Create a form that prompts the user to select a Journal from a set of Journals in a provided folder
- [ ] Add a configuration option to select a Journal folder to use as the source for the opening-crawl
- [ ] Add a button somewhere to launch the opening-crawl (currently thinking scene-control tool bar, but that feels a little wrong)
- [ ] Add support for localization

**Comment by bheiskell** [comment]
I figured out how to get handlebars to work the way I wanted to wire in the data to the Application. Additionally, I ported the JavaScript to time the audio file with the animation, but that will likely get a revamp, because it's not using Foundry's AudioHelper. Lastly, I introduced localization to the project to deal with the static strings in the HTML.

**Comment by wrycu** [comment]
It's probably not worth using Foundry's AudioHelper since 0.8.x is supposed to redo how the Audio system is done.

**Comment by bheiskell** [comment]
Sensible. Rather than doing that I'll just see if I can read a volume setting somewhere and use that instead.

**Comment by wrycu** [comment]
Actually I looked into it and it's really, really lightweight. It's still throwaway work, but it's simple. Here's the sample code I happen to have.
```javascript
AudioHelper.play({src: "Audio/Soundboard/Saber_Attack_1.mp3", volume: .5, autoplay: true, loop: false}, true);
```

**Comment by bheiskell** [comment]
Yeah, what I specifically need to look into is the preload hook. I'm pretty certain it's possible though, and it would clean up some jenky JS.

**Comment by bheiskell** [comment]
Okay we're at an MVP. It's still sharp around the edges. I think I want to add a button to create a new opening session (or add that to the launcher). It would be nice if there was a picker for the journal, audio file, and logo as well.

**Comment by bheiskell** [comment]
@wrycu, I'm trying to ease the initialization so that the Opening Crawl just works out of the box. Should I just pick a default folder name, and create that folder if it doesn't exist when the GM attempts to either launch an Opening Crawl or create a template?

**Comment by wrycu** [comment]
I think that makes sense.

**Comment by bheiskell** [comment]
Audio subsystem is done. Next up is the settings picker. Unfortunately I can't use the linked library because it's not a module and it's GPL'd. I'm going to see if I can emulate this for at least the files selected.

**Comment by bheiskell** [comment]
All set.
